# Generated by Django 5.0 on 2024-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_rename_phone_contactmodel_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/resume.png'),
        ),
    ]
