# Generated by Django 5.0 on 2024-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_delete_projectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
